export const CAREERS_SEED_DATA = [
  {
    title: "Software Engineer",
    description: "Design, develop, and maintain software applications using programming languages and frameworks.",
    educationPath: "Bachelor's in Computer Science or related field; coding bootcamp alternative possible",
    industryOverview: "Tech industry, diverse sectors using software solutions",
    skills: [
      { skillName: "JavaScript/TypeScript", importanceLevel: 5 },
      { skillName: "System Design", importanceLevel: 4 },
      { skillName: "Problem Solving", importanceLevel: 5 },
      { skillName: "Version Control (Git)", importanceLevel: 4 },
      { skillName: "Database Management", importanceLevel: 4 },
    ],
  },
  {
    title: "Data Scientist",
    description: "Analyze complex data sets to inform business decisions using statistical and machine learning techniques.",
    educationPath: "Bachelor's in Statistics, Mathematics, or Computer Science; advanced degree often required",
    industryOverview: "Tech, finance, healthcare, and business analytics sectors",
    skills: [
      { skillName: "Python", importanceLevel: 5 },
      { skillName: "Statistical Analysis", importanceLevel: 5 },
      { skillName: "Machine Learning", importanceLevel: 4 },
      { skillName: "Data Visualization", importanceLevel: 4 },
      { skillName: "SQL", importanceLevel: 4 },
    ],
  },
  {
    title: "UX/UI Designer",
    description: "Create user-centered designs for digital products, focusing on usability and aesthetics.",
    educationPath: "Degree in Design, HCI, or related field; portfolio and design bootcamp also viable",
    industryOverview: "Tech, software, e-commerce, and digital agencies",
    skills: [
      { skillName: "Figma/Adobe XD", importanceLevel: 5 },
      { skillName: "User Research", importanceLevel: 4 },
      { skillName: "Wireframing", importanceLevel: 4 },
      { skillName: "Prototyping", importanceLevel: 4 },
      { skillName: "Visual Design", importanceLevel: 5 },
    ],
  },
  {
    title: "Product Manager",
    description: "Guide product development from concept to launch, balancing user needs with business goals.",
    educationPath: "Business, engineering, or related degree; MBA optional; often transition from other roles",
    industryOverview: "Tech, software, consumer goods, and startups",
    skills: [
      { skillName: "Strategic Thinking", importanceLevel: 5 },
      { skillName: "Communication", importanceLevel: 5 },
      { skillName: "Analytics", importanceLevel: 4 },
      { skillName: "Project Management", importanceLevel: 4 },
      { skillName: "Stakeholder Management", importanceLevel: 5 },
    ],
  },
  {
    title: "DevOps Engineer",
    description: "Manage infrastructure, deployment pipelines, and system reliability for software applications.",
    educationPath: "Bachelor's in Computer Science or IT; certifications in AWS/Azure/GCP valuable",
    industryOverview: "Tech companies, financial services, and enterprise software",
    skills: [
      { skillName: "Docker/Kubernetes", importanceLevel: 5 },
      { skillName: "Linux/Unix", importanceLevel: 5 },
      { skillName: "CI/CD Pipelines", importanceLevel: 4 },
      { skillName: "Cloud Platforms (AWS/Azure)", importanceLevel: 5 },
      { skillName: "Monitoring & Logging", importanceLevel: 4 },
    ],
  },
  {
    title: "Cybersecurity Analyst",
    description: "Protect organizational systems and data from security threats and vulnerabilities.",
    educationPath: "Bachelor's in Cybersecurity or IT; certifications like Security+, CEH recommended",
    industryOverview: "Finance, government, tech, healthcare, and all industries",
    skills: [
      { skillName: "Network Security", importanceLevel: 5 },
      { skillName: "Threat Analysis", importanceLevel: 5 },
      { skillName: "Incident Response", importanceLevel: 4 },
      { skillName: "Penetration Testing", importanceLevel: 4 },
      { skillName: "Security Tools", importanceLevel: 4 },
    ],
  },
  {
    title: "Mobile App Developer",
    description: "Develop applications for mobile platforms including iOS and Android.",
    educationPath: "Bachelor's in Computer Science or related field; mobile-specific bootcamps available",
    industryOverview: "Tech companies, startups, and software development firms",
    skills: [
      { skillName: "Swift/Kotlin", importanceLevel: 5 },
      { skillName: "Mobile UI/UX", importanceLevel: 4 },
      { skillName: "APIs & Backend Integration", importanceLevel: 4 },
      { skillName: "React Native/Flutter", importanceLevel: 4 },
      { skillName: "Testing & Debugging", importanceLevel: 4 },
    ],
  },
  {
    title: "Data Engineer",
    description: "Design and maintain data pipelines and infrastructure for data processing and analytics.",
    educationPath: "Bachelor's in Computer Science, Engineering, or related field",
    industryOverview: "Tech, finance, healthcare, e-commerce, and big data companies",
    skills: [
      { skillName: "SQL", importanceLevel: 5 },
      { skillName: "Apache Spark/Hadoop", importanceLevel: 4 },
      { skillName: "Python/Scala", importanceLevel: 5 },
      { skillName: "ETL Processes", importanceLevel: 5 },
      { skillName: "Cloud Databases", importanceLevel: 4 },
    ],
  },
  {
    title: "Business Analyst",
    description: "Bridge business and technology by analyzing processes and requirements for system improvements.",
    educationPath: "Bachelor's in Business, IT, or related field; certifications like CBAP optional",
    industryOverview: "Finance, healthcare, government, consulting, and most industries",
    skills: [
      { skillName: "Requirements Gathering", importanceLevel: 5 },
      { skillName: "Data Analysis", importanceLevel: 4 },
      { skillName: "Process Mapping", importanceLevel: 4 },
      { skillName: "Communication", importanceLevel: 5 },
      { skillName: "SQL Basics", importanceLevel: 3 },
    ],
  },
  {
    title: "Full-Stack Developer",
    description: "Build complete web applications handling both frontend and backend development.",
    educationPath: "Bachelor's in Computer Science; coding bootcamps widely accepted",
    industryOverview: "Tech startups, software companies, and agencies",
    skills: [
      { skillName: "JavaScript/TypeScript", importanceLevel: 5 },
      { skillName: "React/Vue/Angular", importanceLevel: 5 },
      { skillName: "Node.js/Django/Rails", importanceLevel: 4 },
      { skillName: "Database Design", importanceLevel: 4 },
      { skillName: "REST APIs", importanceLevel: 4 },
    ],
  },
  {
    title: "Cloud Architect",
    description: "Design scalable cloud infrastructure and solutions for enterprise organizations.",
    educationPath: "Bachelor's in IT/Computer Science; AWS/Azure/GCP certifications essential",
    industryOverview: "Enterprise tech, financial services, and large organizations",
    skills: [
      { skillName: "AWS/Azure/GCP", importanceLevel: 5 },
      { skillName: "System Architecture", importanceLevel: 5 },
      { skillName: "Security Design", importanceLevel: 4 },
      { skillName: "Cost Optimization", importanceLevel: 4 },
      { skillName: "Infrastructure as Code", importanceLevel: 4 },
    ],
  },
  {
    title: "AI/Machine Learning Engineer",
    description: "Develop artificial intelligence and machine learning models for various applications.",
    educationPath: "Bachelor's/Master's in Computer Science, Math, or Physics; deep learning specialization",
    industryOverview: "Tech giants, startups, research, healthcare, and finance",
    skills: [
      { skillName: "Python", importanceLevel: 5 },
      { skillName: "TensorFlow/PyTorch", importanceLevel: 5 },
      { skillName: "Statistical Analysis", importanceLevel: 5 },
      { skillName: "Neural Networks", importanceLevel: 4 },
      { skillName: "Model Deployment", importanceLevel: 4 },
    ],
  },
  {
    title: "QA/Testing Engineer",
    description: "Ensure software quality through comprehensive testing, automation, and bug identification.",
    educationPath: "Bachelor's in Computer Science or IT; certification in ISTQB or similar valued",
    industryOverview: "Software companies, game development, fintech, and tech firms",
    skills: [
      { skillName: "Test Automation", importanceLevel: 5 },
      { skillName: "Selenium/Cypress", importanceLevel: 4 },
      { skillName: "Manual Testing", importanceLevel: 4 },
      { skillName: "Bug Tracking Tools", importanceLevel: 4 },
      { skillName: "Performance Testing", importanceLevel: 3 },
    ],
  },
  {
    title: "Solutions Architect",
    description: "Design technical solutions aligned with business requirements for client organizations.",
    educationPath: "Bachelor's in IT/Computer Science; 5+ years experience often required",
    industryOverview: "Consulting firms, tech companies, and enterprise software providers",
    skills: [
      { skillName: "System Architecture", importanceLevel: 5 },
      { skillName: "Client Management", importanceLevel: 5 },
      { skillName: "Technical Documentation", importanceLevel: 4 },
      { skillName: "Problem Solving", importanceLevel: 5 },
      { skillName: "Cloud Platforms", importanceLevel: 4 },
    ],
  },
  {
    title: "Frontend Developer",
    description: "Create responsive, interactive user interfaces and web experiences using modern frameworks.",
    educationPath: "Bachelor's in Computer Science; web development bootcamp alternative common",
    industryOverview: "Tech companies, agencies, startups, and e-commerce platforms",
    skills: [
      { skillName: "HTML/CSS", importanceLevel: 5 },
      { skillName: "JavaScript/TypeScript", importanceLevel: 5 },
      { skillName: "React/Vue/Angular", importanceLevel: 5 },
      { skillName: "Responsive Design", importanceLevel: 4 },
      { skillName: "Web Performance", importanceLevel: 3 },
    ],
  },
  {
    title: "Backend Developer",
    description: "Build server-side logic, databases, and APIs that power applications and services.",
    educationPath: "Bachelor's in Computer Science; backend-focused bootcamp also viable",
    industryOverview: "Tech companies, financial institutions, streaming services, and startups",
    skills: [
      { skillName: "Python/Java/C#", importanceLevel: 5 },
      { skillName: "API Design", importanceLevel: 4 },
      { skillName: "Database Design", importanceLevel: 5 },
      { skillName: "Microservices", importanceLevel: 4 },
      { skillName: "SQL & NoSQL", importanceLevel: 4 },
    ],
  },
];
