export const ROADMAP_SEED_DATA = [
  {
    careerTitle: 'Software Engineer',
    title: 'Software Engineer Learning Roadmap',
    description: 'A structured path to becoming a professional software engineer.',
    steps: [
      { title: 'Learn Programming Fundamentals', description: 'Master a language like JavaScript or Python, covering variables, loops, functions, and OOP.', stepOrder: 1 },
      { title: 'Data Structures & Algorithms', description: 'Study arrays, linked lists, trees, sorting, and searching algorithms.', stepOrder: 2 },
      { title: 'Version Control with Git', description: 'Learn Git basics — branching, merging, pull requests, and GitHub workflows.', stepOrder: 3 },
      { title: 'System Design Basics', description: 'Understand how to design scalable systems, APIs, and databases.', stepOrder: 4 },
      { title: 'Build & Deploy Projects', description: 'Build at least 3 real projects and deploy them using cloud services.', stepOrder: 5 },
    ],
  },
  {
    careerTitle: 'Data Scientist',
    title: 'Data Scientist Learning Roadmap',
    description: 'Step-by-step guide to becoming a data scientist.',
    steps: [
      { title: 'Python for Data Science', description: 'Learn Python with NumPy, Pandas, and Matplotlib for data manipulation and visualization.', stepOrder: 1 },
      { title: 'Statistics & Probability', description: 'Cover descriptive statistics, probability distributions, hypothesis testing, and regression.', stepOrder: 2 },
      { title: 'Machine Learning Fundamentals', description: 'Study supervised and unsupervised learning algorithms using scikit-learn.', stepOrder: 3 },
      { title: 'SQL & Data Wrangling', description: 'Learn SQL for querying databases and cleaning messy real-world datasets.', stepOrder: 4 },
      { title: 'Data Science Projects', description: 'Complete end-to-end projects with real datasets and publish on GitHub/Kaggle.', stepOrder: 5 },
    ],
  },
  {
    careerTitle: 'UX/UI Designer',
    title: 'UX/UI Designer Learning Roadmap',
    description: 'A path to becoming a professional UX/UI designer.',
    steps: [
      { title: 'Design Fundamentals', description: 'Learn color theory, typography, layout, and visual hierarchy.', stepOrder: 1 },
      { title: 'Master Figma', description: 'Get proficient with Figma for wireframing, prototyping, and design systems.', stepOrder: 2 },
      { title: 'User Research Methods', description: 'Study user interviews, usability testing, and persona creation.', stepOrder: 3 },
      { title: 'Build a Portfolio', description: 'Create 3-5 case studies showcasing your design process and outcomes.', stepOrder: 4 },
      { title: 'Responsive & Accessible Design', description: 'Learn to design for multiple screen sizes and accessibility standards.', stepOrder: 5 },
    ],
  },
  {
    careerTitle: 'Frontend Developer',
    title: 'Frontend Developer Learning Roadmap',
    description: 'A structured path to becoming a frontend developer.',
    steps: [
      { title: 'HTML & CSS Mastery', description: 'Build solid foundations with semantic HTML, CSS Flexbox, Grid, and responsive design.', stepOrder: 1 },
      { title: 'JavaScript Essentials', description: 'Learn core JS concepts — DOM manipulation, events, async/await, and ES6+.', stepOrder: 2 },
      { title: 'React Framework', description: 'Master React including hooks, state management, and component architecture.', stepOrder: 3 },
      { title: 'Web Performance', description: 'Learn lazy loading, code splitting, caching, and performance optimization techniques.', stepOrder: 4 },
      { title: 'Deploy Frontend Projects', description: 'Deploy projects using Vercel or Netlify and build a portfolio.', stepOrder: 5 },
    ],
  },
  {
    careerTitle: 'Backend Developer',
    title: 'Backend Developer Learning Roadmap',
    description: 'A structured guide to becoming a backend developer.',
    steps: [
      { title: 'Server-Side Language', description: 'Learn Node.js, Python, or Java for backend development.', stepOrder: 1 },
      { title: 'REST API Design', description: 'Build and document RESTful APIs following best practices.', stepOrder: 2 },
      { title: 'Database Design', description: 'Learn relational databases (PostgreSQL) and NoSQL (MongoDB) with proper schema design.', stepOrder: 3 },
      { title: 'Authentication & Security', description: 'Implement JWT auth, hashing, and secure API practices.', stepOrder: 4 },
      { title: 'Deployment & DevOps Basics', description: 'Deploy backend apps using Docker and cloud platforms like AWS or Railway.', stepOrder: 5 },
    ],
  },
  {
    careerTitle: 'Product Manager',
    title: 'Product Manager Learning Roadmap',
    description: 'A structured path to becoming a successful product manager.',
    steps: [
      { title: 'Understand Product Management Basics', description: 'Learn the role of a PM, product lifecycle, and how to work with cross-functional teams.', stepOrder: 1 },
      { title: 'Learn Agile & Scrum', description: 'Master agile methodologies, sprint planning, and backlog management.', stepOrder: 2 },
      { title: 'Develop Communication Skills', description: 'Practice stakeholder management, presentations, and writing clear product requirements.', stepOrder: 3 },
      { title: 'Analytics & Data Driven Decisions', description: 'Learn to use analytics tools to measure product performance and drive decisions.', stepOrder: 4 },
      { title: 'Build a Product Case Study', description: 'Create a real or hypothetical product case study to showcase your PM thinking.', stepOrder: 5 },
    ],
  },
  {
    careerTitle: 'DevOps Engineer',
    title: 'DevOps Engineer Learning Roadmap',
    description: 'A step-by-step path to becoming a DevOps engineer.',
    steps: [
      { title: 'Linux & Command Line', description: 'Get comfortable with Linux, shell scripting, and command line tools.', stepOrder: 1 },
      { title: 'Learn Docker & Containers', description: 'Understand containerization, Docker commands, and building images.', stepOrder: 2 },
      { title: 'CI/CD Pipelines', description: 'Set up automated build, test, and deployment pipelines using GitHub Actions or Jenkins.', stepOrder: 3 },
      { title: 'Cloud Platforms', description: 'Learn AWS, Azure, or GCP basics including compute, storage, and networking.', stepOrder: 4 },
      { title: 'Kubernetes & Orchestration', description: 'Deploy and manage containerized applications at scale using Kubernetes.', stepOrder: 5 },
    ],
  },
  {
    careerTitle: 'Cybersecurity Analyst',
    title: 'Cybersecurity Analyst Learning Roadmap',
    description: 'A structured guide to starting a career in cybersecurity.',
    steps: [
      { title: 'Networking Fundamentals', description: 'Learn TCP/IP, DNS, HTTP, firewalls, and how networks communicate.', stepOrder: 1 },
      { title: 'Security Concepts', description: 'Study CIA triad, common attack vectors, encryption, and security protocols.', stepOrder: 2 },
      { title: 'Security Tools', description: 'Get hands-on with tools like Wireshark, Nmap, Metasploit, and Burp Suite.', stepOrder: 3 },
      { title: 'Threat Analysis & Incident Response', description: 'Learn how to detect threats, analyze logs, and respond to security incidents.', stepOrder: 4 },
      { title: 'Certifications', description: 'Prepare for CompTIA Security+, CEH, or similar entry-level security certifications.', stepOrder: 5 },
    ],
  },
  {
    careerTitle: 'Mobile App Developer',
    title: 'Mobile App Developer Learning Roadmap',
    description: 'A structured path to building mobile applications.',
    steps: [
      { title: 'Choose a Platform', description: 'Decide between native (Swift/Kotlin) or cross-platform (React Native/Flutter) development.', stepOrder: 1 },
      { title: 'Learn Core Language', description: 'Master Swift for iOS or Kotlin for Android, or Dart for Flutter.', stepOrder: 2 },
      { title: 'Mobile UI/UX Principles', description: 'Study mobile design patterns, navigation, and platform-specific UI guidelines.', stepOrder: 3 },
      { title: 'APIs & Backend Integration', description: 'Connect mobile apps to REST APIs, handle authentication, and manage state.', stepOrder: 4 },
      { title: 'Publish an App', description: 'Build a complete app and publish it to the App Store or Google Play.', stepOrder: 5 },
    ],
  },
  {
    careerTitle: 'Data Engineer',
    title: 'Data Engineer Learning Roadmap',
    description: 'A step-by-step guide to becoming a data engineer.',
    steps: [
      { title: 'SQL Mastery', description: 'Master advanced SQL — window functions, CTEs, query optimization, and indexing.', stepOrder: 1 },
      { title: 'Python for Data Engineering', description: 'Learn Python with Pandas, and scripting for data processing and automation.', stepOrder: 2 },
      { title: 'ETL Pipelines', description: 'Build Extract, Transform, Load pipelines using tools like Apache Airflow.', stepOrder: 3 },
      { title: 'Big Data Tools', description: 'Learn Apache Spark and Hadoop for processing large-scale datasets.', stepOrder: 4 },
      { title: 'Cloud Data Platforms', description: 'Work with cloud databases like BigQuery, Redshift, or Azure Synapse.', stepOrder: 5 },
    ],
  },
  {
    careerTitle: 'Business Analyst',
    title: 'Business Analyst Learning Roadmap',
    description: 'A structured path to becoming a business analyst.',
    steps: [
      { title: 'Business Analysis Fundamentals', description: 'Learn core BA concepts, stakeholder analysis, and requirements gathering techniques.', stepOrder: 1 },
      { title: 'Process Mapping & Documentation', description: 'Master tools like Visio or Lucidchart for process flows and documentation.', stepOrder: 2 },
      { title: 'Data Analysis Basics', description: 'Learn Excel, SQL basics, and how to interpret data for business decisions.', stepOrder: 3 },
      { title: 'Communication & Presentation', description: 'Practice writing business requirements documents and presenting findings to stakeholders.', stepOrder: 4 },
      { title: 'BA Certification', description: 'Prepare for CBAP or Entry Certificate in Business Analysis (ECBA) certification.', stepOrder: 5 },
    ],
  },
  {
    careerTitle: 'Full-Stack Developer',
    title: 'Full-Stack Developer Learning Roadmap',
    description: 'A complete path to becoming a full-stack developer.',
    steps: [
      { title: 'Frontend Foundations', description: 'Master HTML, CSS, JavaScript, and a frontend framework like React or Vue.', stepOrder: 1 },
      { title: 'Backend Development', description: 'Learn Node.js, Express, or Django for building server-side APIs.', stepOrder: 2 },
      { title: 'Database Design', description: 'Work with both SQL (PostgreSQL) and NoSQL (MongoDB) databases.', stepOrder: 3 },
      { title: 'Authentication & Security', description: 'Implement JWT auth, session management, and secure API practices.', stepOrder: 4 },
      { title: 'Deploy Full-Stack Apps', description: 'Deploy complete applications using services like Vercel, Railway, or AWS.', stepOrder: 5 },
    ],
  },
  {
    careerTitle: 'Cloud Architect',
    title: 'Cloud Architect Learning Roadmap',
    description: 'A structured path to becoming a cloud architect.',
    steps: [
      { title: 'Cloud Fundamentals', description: 'Learn core cloud concepts — compute, storage, networking, and pricing models.', stepOrder: 1 },
      { title: 'AWS/Azure/GCP Certification', description: 'Earn a foundational cloud certification like AWS Solutions Architect Associate.', stepOrder: 2 },
      { title: 'System Architecture Patterns', description: 'Study microservices, serverless, event-driven, and high availability architectures.', stepOrder: 3 },
      { title: 'Security & Cost Optimization', description: 'Learn IAM, encryption, compliance, and cloud cost management strategies.', stepOrder: 4 },
      { title: 'Infrastructure as Code', description: 'Use Terraform or AWS CloudFormation to provision and manage infrastructure.', stepOrder: 5 },
    ],
  },
  {
    careerTitle: 'AI/Machine Learning Engineer',
    title: 'AI/ML Engineer Learning Roadmap',
    description: 'A structured path to becoming an AI/ML engineer.',
    steps: [
      { title: 'Python & Math Foundations', description: 'Strengthen Python skills and study linear algebra, calculus, and probability.', stepOrder: 1 },
      { title: 'Machine Learning Fundamentals', description: 'Learn supervised, unsupervised, and reinforcement learning algorithms.', stepOrder: 2 },
      { title: 'Deep Learning & Neural Networks', description: 'Study neural network architectures using TensorFlow or PyTorch.', stepOrder: 3 },
      { title: 'Model Training & Evaluation', description: 'Learn to train, evaluate, tune, and validate ML models on real datasets.', stepOrder: 4 },
      { title: 'Model Deployment', description: 'Deploy ML models as APIs using FastAPI or Flask, and containerize with Docker.', stepOrder: 5 },
    ],
  },
  {
    careerTitle: 'QA/Testing Engineer',
    title: 'QA/Testing Engineer Learning Roadmap',
    description: 'A structured path to becoming a QA/testing engineer.',
    steps: [
      { title: 'Testing Fundamentals', description: 'Learn types of testing — unit, integration, system, regression, and UAT.', stepOrder: 1 },
      { title: 'Manual Testing', description: 'Practice writing test cases, test plans, and bug reports using tools like Jira.', stepOrder: 2 },
      { title: 'Test Automation', description: 'Learn Selenium or Cypress for automated browser testing.', stepOrder: 3 },
      { title: 'API Testing', description: 'Use Postman or REST Assured to test backend APIs systematically.', stepOrder: 4 },
      { title: 'Performance Testing', description: 'Learn JMeter or k6 to run load and stress tests on applications.', stepOrder: 5 },
    ],
  },
  {
    careerTitle: 'Solutions Architect',
    title: 'Solutions Architect Learning Roadmap',
    description: 'A structured path to becoming a solutions architect.',
    steps: [
      { title: 'Technical Foundations', description: 'Build strong knowledge of system design, networking, databases, and cloud platforms.', stepOrder: 1 },
      { title: 'Architecture Patterns', description: 'Study enterprise architecture patterns — SOA, microservices, event-driven design.', stepOrder: 2 },
      { title: 'Client & Stakeholder Management', description: 'Learn how to gather requirements, manage expectations, and present solutions.', stepOrder: 3 },
      { title: 'Technical Documentation', description: 'Practice writing architecture diagrams, solution proposals, and technical specs.', stepOrder: 4 },
      { title: 'Cloud & Integration Certifications', description: 'Earn certifications like AWS Solutions Architect Professional or TOGAF.', stepOrder: 5 },
    ],
  },
];